messager_pub:
    resource: "@MessagerBundle/Resources/config/routing/pub.yml"
    prefix:   /pub

messager_notification:
    resource: "@MessagerBundle/Resources/config/routing/notification.yml"
    prefix:   /notification

messager_sending:
    resource: "@MessagerBundle/Resources/config/routing/sending.yml"
    prefix:   /sending
    
formated:
    resource: "@MessagerBundle/Resources/config/routing/formated.yml"
    prefix:   /formated


messager_homepage:
    path:     /messager
    defaults: { _controller: MessagerBundle:Default:index }
