abonnement_index:
    path:     /
    defaults: { _controller: "AdminBundle:Abonnement:index" }
    methods:  GET

abonnement_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Abonnement:show" }
    methods:  GET

abonnement_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Abonnement:new" }
    methods:  [GET, POST]

abonnement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Abonnement:edit" }
    methods:  [GET, POST]

abonnement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Abonnement:delete" }
    methods:  DELETE
