ambassador_index:
    path:     /
    defaults: { _controller: "AdminBundle:Ambassador:index" }
    methods:  GET

ambassador_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Ambassador:show" }
    methods:  GET

ambassador_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Ambassador:new" }
    methods:  [GET, POST]

ambassador_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Ambassador:edit" }
    methods:  [GET, POST]

ambassador_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Ambassador:delete" }
    methods:  DELETE
