abonnement_index_json:
    path:     /abonnement/{studentId}/json
    defaults: { _controller: "AdminBundle:Abonnement:indexJson"}
    methods:  GET

abonnement_new_json:
    path:     /abonnement/{id}/new/json
    defaults: { _controller: "AdminBundle:Abonnement:newJson" ,id:0}
    methods:  [GET,POST]
  
abonnement_show_json:
    path:     /abonnement/{studentId}/{id}/json
    defaults: { _controller: "AdminBundle:Abonnement:showJson"}
    methods:  [GET,POST] 

candidat_new_json:
    path:     /candidat/{studentId}/new/json
    defaults: { _controller: "AdminBundle:Candidat:newJson" }
    methods:  [GET,POST]
  
candidat_show_json:
    path:     /candidat/{studentId}/json
    defaults: { _controller: "AdminBundle:Candidat:showJson"}
    methods:  [GET,POST] 

info_new_json:
    path:     /info/{email}/new/json
    defaults: { _controller: "AdminBundle:Info:newJson" }
    methods:  [GET,POST]
 
info_edit_picture:
    path:     /info/{email}/picture
    defaults: { _controller: "AdminBundle:Info:editPicture" }
    methods:  [GET,POST] 

info_show_json:
    path:     /info/{email}/json
    defaults: { _controller: "AdminBundle:Info:showJson"}
    methods:  [GET,POST] 


analyse_new_json:
    path:     /analyse/{studentId}/{concours}/{matiere}/{partie}/new/json
    defaults: { _controller: "AdminBundle:Analyse:newJson" ,matiere:0,partie:0}
    methods:  [GET,POST]
  
analyse_show_json:
    path:     /analyse/{studentId}/{concours}/{matiere}/{partie}/json
    defaults: { _controller: "AdminBundle:Analyse:showJson",matiere:0,partie:0}
    methods:  [GET,POST]      
