price_index:
    path:     /
    defaults: { _controller: "AdminBundle:Price:index" }
    methods:  GET

price_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Price:show" }
    methods:  GET

price_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Price:new" }
    methods:  [GET, POST]

price_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Price:edit" }
    methods:  [GET, POST]

price_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Price:delete" }
    methods:  DELETE
