ressource_index:
    path:     /{session}
    defaults: { _controller: "AdminBundle:Ressource:index" ,"session":0}
    methods:  GET

ressource_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Ressource:show" }
    methods:  GET

ressource_new:
    path:     /new/{session}
    defaults: { _controller: "AdminBundle:Ressource:new" ,"session":0}
    methods:  [GET, POST]

ressource_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Ressource:edit" }
    methods:  [GET, POST]

ressource_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Ressource:delete" }
    methods:  DELETE
