Pwm\MessagerBundle\Entity\Sending:
    exclusion_policy: none
    properties:
        id:
             groups: ['sending', 'full']             
        registrationId:
             groups: ['sending', 'full']
        readed:
             groups: ['sending', 'full']
        sendDate:
             groups: ['sending', 'full']
             expose: true
             type: DateTime<'Y-m-d'>               
        notification:
             groups: ['sending', 'full']
