Pwm\MessagerBundle\Entity\Pub:
    exclusion_policy: none
    properties:
        id:
             groups: ['pub', 'full']             
        nomDeCampagne:
             groups: ['pub', 'full']
        type:
             groups: ['pub', 'full']
        base64Image:
             groups: ['pub', 'full']              
        html:
             groups: ['pub', 'full']
        text:
             groups: ['pub', 'full']