Pwm\MessagerBundle\Entity\Notification:
    exclusion_policy: none
    properties:
        id:
             groups: ['sending', 'full']             
        titre:
             groups: ['sending', 'full']
        sousTitre:
             groups: ['sending', 'full']
        text:
             groups: ['sending', 'full']
        format:
             groups: ['sending', 'full']             
        url:
             groups: ['sending', 'full']
        image:
            groups: ['question', 'full']             
        callback_methods:
             pre_serialize: ['getImage']