<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Programme;
/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends EntityRepository
{
	 /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findForMe($studentId){
         $qb = $this->createQueryBuilder('a')->where('a.studentId=:studentId')->setParameter('studentId',$studentId); 

          return $qb->getQuery()->getResult();
  }


	 /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findOneForMe($studentId,Programme $programme){
         $qb = $this->createQueryBuilder('a')
         ->where('a.studentId=:studentId')->setParameter('studentId',$studentId)
         ->andWhere('a.programme=:programme')->setParameter('programme',$programme);

          return $qb->getQuery()->getOneOrNullResult();
  }
}
