<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationRepository extends EntityRepository
{
       public function findList($region=null, $startDate=null, $endDate=null){
         $qb = $this->createQueryBuilder('a')->join('a.client','c');
        if($region!=null){
           $qb->where('c.ville=:ville')
          ->setParameter('ville', $region);
          }
      if($startDate!=null){
           $qb->andWhere('a.date>=:startDate')
          ->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('a.date<=:endDate')
          ->setParameter('endDate',new \DateTime($endDate));
          }          
          return $qb->getQuery()->getArrayResult();
  }   


  
}
