<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

  /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findList($start){
         $qb = $this->createQueryBuilder('a')->orderBy('a.date', 'desc'); 
         $query=$qb->getQuery();
         $query->setFirstResult($start)->setMaxResults(2);
          return $query->getResult();
  }
    function findByUser($article, $uid){
       $qb =$this->createQueryBuilder('a')
       ->where('a.id=:article') ->setParameter('article', $article) ->leftJoin('a.infos', 'i');
        return   $qb->andWhere('i.uid=:uid')->setParameter('uid', $uid)->getQuery()->getResult();
    }
}
