<?php

namespace AppBundle\Repository;

/**
 * CampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneRepository extends \Doctrine\ORM\EntityRepository
{
}
