<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChargementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargementRepository extends EntityRepository
{

public function findByClient($user=null ,$dateSave=null)
{
  $qb = $this->createQueryBuilder('c');
		 
      $qb ->orderBy('c.dateSave', 'DESC');
  return $qb->getQuery()
     ->getArrayResult();
  

}
}
