<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function findUsers()

{

  $qb = $this->createQueryBuilder('c');

  return $qb

    ->getQuery()

    ->getArrayResult();

  

}
}
