<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
	public function findCommandeByStatus($status=null)
{
  $qb = $this->createQueryBuilder('c')
  ->where('c.dateSave < :today')
       ->setParameter('today', new \DateTime());
	 if($status!=null){
		$qb->andWhere('c.status = :status')
          ->setParameter('status', $status);
	 }     
     $qb->orderBy('c.dateSave', 'DESC');
  return $qb
     ->getQuery()
    ->getArrayResult();
  ;

}
}
