<?php

namespace AppBundle\Repository;
use AppBundle\Entity\PointVente; 
use AppBundle\Entity\User; 
/**
 * CommendeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommendeRepository extends \Doctrine\ORM\EntityRepository
{
	  	 public function findByPointVente(PointVente $pointVente){
           $qb = $this->createQueryBuilder('c')->where('c.pointVente=:pointVente')->setParameter('pointVente', $pointVente);
         return $qb->getQuery()->getResult();  
  }

  	  	public function findAll(User $user,$startDate=null, $endDate=null){
           $qb = $this->createQueryBuilder('c')->where('c.pointVente=:pointVente')->setParameter('pointVente', $pointVente);
           if($user!=null){
           $qb ->andWhere('c.user=:user')->setParameter('user', $user);
            }
             if($startDate!=null){
           $qb->andWhere('c.date is null or c.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('c.date is null or c.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }
         return $qb->getQuery()->getResult();  
  }
}
