<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{

  public function findOneByUser(User $user){
 $qb =$this->createQueryBuilder('a')
       ->where('a.user=:user') ->setParameter('user', $user)->andWhere('a.status is NULL');
        return   $qb->getQuery()->getOneOrNullResult();
 }
}
