<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProduitRepository extends EntityRepository
{


	public function findByClient( $commandeClient=null )
{
  $qb = $this->createQueryBuilder('c');
  if (!is_null($commandeClient)) {
  $qb->where('c.commandeClient =:commandeClient')
       ->setParameter('commandeClient', $commandeClient );
  } 	 
      $qb ->orderBy('c.dateSave', 'DESC');
  return $qb->getQuery()
     ->getArrayResult();
  ;

}

}
