<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeClientRepository extends EntityRepository
{
public function findCommandeByDate($user=null,$dateSave=null,$pointVente=null)
{
  $qb = $this->createQueryBuilder('c')->join('c.pointVente','p');
  if(!is_null($dateSave)){
      $qb->where('c.date=:dateSave')
       ->setParameter('dateSave', new \DateTime($dateSave));
        }    
	 if(!is_null($user)){
		$qb->andWhere('c.user= :user')->setParameter('user', $user);
	  }  
    if(!is_null($pointVente)){
    $qb->where('p.nom LIKE :nom')
               ->setParameter('nom', '%'.$pointVente.'%');
        }     
     $qb->orderBy('c.date', 'DESC');
  return $qb
     ->getQuery()
    ->getArrayResult();
  ;
}

public function findCommendeOuverte($user, $pointVente)
  {
    $qb = $this->createQueryBuilder('c')
  ->where('c.user =:user')
  ->andWhere('c.pointVente=:pointVente')
  ->andWhere('c.status=:status')
  ->setParameter('user',$user)
  ->setParameter('pointVente',$pointVente); 
  ->setParameter('status',"ouverte"); 
       $qb->orderBy('m.date', 'DESC');
  return $qb
     ->getQuery()
     ->getOneOrNullResult();
  ;

}
}
