<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Campagne;
/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findList(Campagne $campagne){
        $qb = $this->createQueryBuilder('p')
        ->where('p.campagne=:campagne')
        ->setParameter('campagne',$campagne)
        ->orderBy('p.date', 'asc'); 
        $query=$qb->getQuery();
         return $query->getResult();
 }
}
