<?php

namespace AppBundle\Repository;

/**
 * ExplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
