<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{

	public function findLastMenus()
{
  $qb = $this->createQueryBuilder('m')
  ->where('m.dateSave <= :toMonth')
       ->setParameter('toMonth', new \DateTime('+30 day')); 
     $qb->orderBy('m.dateSave', 'DESC');
  return $qb
     ->getQuery()
    ->getArrayResult();
  ;

}

public function findTodayMenu()
  {
    $dateObject = new \DateTime();
  	$date = $dateObject->format('d-m-Y');
  $qb = $this->createQueryBuilder('m')
  ->where('m.dateSave >= :toDay')
       ->setParameter('toDay', \DateTime::createFromFormat('d-m-Y',$date)); 
     $qb->orderBy('m.dateSave', 'DESC');
  return $qb
     ->getQuery()
    ->getOneOrNullResult();
  ;

}
}
