<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{

	public function findLastMenus()
{
  $qb = $this->createQueryBuilder('m')
  ->where('m.dateSave <= :toMonth')
       ->setParameter('toMonth', new \DateTime('+30 day')); 
     $qb->orderBy('m.dateSave', 'DESC');
  return $qb
     ->getQuery()
    ->getArrayResult();
  ;

}

public function findTodayMenu()
  {
    $dateObject = new \DateTime('now');
    $dateObject->setTime(0, 0, 0); // Modify to 2013-06-10 00:00:00, beginning of the day   
    $yesteDay=$dateObject->modify('-1 day'); // Have 2013-06-11 00:00:00   
  $qb = $this->createQueryBuilder('m')
  ->where('m.dateSave > :yesteDay')
       ->setParameter('yesteDay',$yesteDay); 
     $qb->orderBy('m.dateSave', 'DESC');
  return $qb
     ->getQuery()
    ->getOneOrNullResult();
  ;

}
}
