<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends EntityRepository
{


    function findByMatiere($partie,$session){
       $qb =$this->createQueryBuilder('a')
       ->where('a.id=:partie')->setParameter('partie', $partie)->leftJoin('a.sessions', 's');
        return   $qb->andWhere('s.id=:sesion')->setParameter('sesion', $sesion)->getQuery()->getResult();
    }
}
