<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoningRepository extends EntityRepository
{
    public function findList($region=null, $startDate=null, $endDate=null){
         $qb = $this->createQueryBuilder('p')->join('p.client','c');
        if($region!=null){
           $qb->where('c.ville=:ville')
          ->setParameter('ville', $region);
          }
      if($startDate!=null){
           $qb->andWhere('p.date>=:startDate')
          ->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('p.date<=:endDate')
          ->setParameter('endDate',new \DateTime($endDate));
          }          
          return $qb->getQuery()->getArrayResult();
  }   
  
      
}
