<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Menu;
/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends EntityRepository
{
	
	public function findAllPlats(Menu $menu=null )
{

  $qb = $this->createQueryBuilder('p');
  if (!is_null($menu)) {
  $qb->where('p.menu >=:menu')
       ->setParameter('menu', $menu );
  }
  	 
      $qb ->orderBy('p.dateSave', 'DESC');
  return $qb->getQuery()
     ->getArrayResult();
  ;

}
}
