<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User; 

/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends \Doctrine\ORM\EntityRepository
{
		      public function findByUser(User $user,$start=0,$all=false,$keys=[""]){
           $qb = $this->createQueryBuilder('p');
           $qb->where('p.user=:user') ->setParameter('user', $user);
            $qb->andWhere($qb->expr()->notIn('p.id', $keys)); 
          return  ($all) ? $qb->getQuery()->setFirstResult($start)->getResult() : $qb->getQuery()->setFirstResult($start)->setMaxResults(100)->getResult() ; 
  }
}
