<?php

namespace AppBundle\Repository;
use AppBundle\Entity\PointVente; 
use AppBundle\Entity\User; 
/**
 * RendezvousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezvousRepository extends \Doctrine\ORM\EntityRepository
{

      public function findByUser(User $user=null,$keys=[0]){
        $qb = $this->createQueryBuilder('p')->leftJoin('p.user','u');
        if ($user->isMe()) {
             $qb->where('u.parent=:user')->setParameter('user', $user);
        }else
            $qb->where('p.user=:user')->setParameter('user', $user); 
          $qb->andWhere($qb->expr()->notIn('p.id', $keys));     
          return $qb->getQuery()->setMaxResults(100)->getResult(); 
  }


}
