<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User; 
/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends \Doctrine\ORM\EntityRepository
{

	    public function findByUserParent(User $parent, User $user ){
           $qb = $this->createQueryBuilder('r')
          ->where('r.parent=:parent')->setParameter('parent', $parent)
          ->andWhere('r.user=:user')->setParameter('user', $user);
         return $qb->getQuery()->getOneOrNullResult();  
  }
}
