<?php

namespace AppBundle\Repository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurRepository extends \Doctrine\ORM\EntityRepository
{

	      public function findByUser(User $user,$start=0,$all=false){
           $qb = $this->createQueryBuilder('p');
           $qb->where('p.user=:user') ->setParameter('user', $user);
          return  ($all) ? $qb->getQuery()->setFirstResult($start)->getResult() : $qb->getQuery()->setFirstResult($start)->setMaxResults(100)->getResult() ; 
  }
}
