<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SituationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationRepository extends EntityRepository
{



  //situation comparee
  public function stockParProduitPeriode ($region=null, $startDate=null, $endDate=null){
    $em = $this->_em;
    $RAW_QUERY =($region!=null) ?'select * from (select p.id, p.nom,count(s.map) as map, count(s.rpp) as rpp, count(s.rpd) as rpd, sum(s.stock) as sd, sum(s.stockg) as sg, sum(s.mvj) as mvj, sum(s.ecl) as ecl from (select v.id,v.date from (select pv.id as pv , max(v.date) as date from point_vente pv join visite v  on pv.id=v.point_vente_id and v.date>=:startDate and v.date<=:endDate and pv.ville=:region group by  pv.id order by pv.id) as u  join  visite v on (u.pv=v.point_vente_id and u.date=v.date) ) as v join situation s on v.id=s.visite_id join (select p.nom, p.id, c.nom as nomCon from produit p left join produit c on p.concurent_id=c.id) p on p.id=s.produit_id group by p.nom,p.id) prod join produit p on prod.id=p.id;
'  : 'select * from (select p.id, p.nom, count(s.map) as map, count(s.rpp) as rpp, count(s.rpd) as rpd, sum(s.stock) as sd, sum(s.stockg) as sg, sum(s.mvj) as mvj, sum(s.ecl) as ecl from (select v.id,v.date from (select pv.id as pv , max(v.date) as date from point_vente pv join visite v  on pv.id=v.point_vente_id and v.date>=:startDate and v.date<=:endDate group by  pv.id order by pv.id) as u  join  visite v on (u.pv=v.point_vente_id and u.date=v.date) ) as v join situation s on v.id=s.visite_id join (select p.nom, p.id, c.nom as nomCon from produit p left join produit c on p.concurent_id=c.id) p on p.id=s.produit_id group by p.nom,p.id) prod join produit p on prod.id=p.id;'; 
  $statement = $em->getConnection()->prepare($RAW_QUERY);
        if($region!=null){
   $statement->bindValue('region', $region);
          }
    $startDate=new \DateTime($startDate);
    $endDate=new \DateTime($endDate);

     $statement->bindValue('startDate', $startDate->format('Y-m-d'));
     $statement->bindValue('endDate',  $endDate->format('Y-m-d'));
     $statement->execute();

      return  $result = $statement->fetchAll();
  }  

//situation comparee
  public function stockParProduitDernier ($region=null, $startDate=null, $endDate=null){
    $em = $this->_em;
    $RAW_QUERY =($region!=null) ?'select p.id,situation.sd,situation.presence,p.dossier from (select id,  sum(sd) as sd, sum(presence) as presence from (select v.pv, p.id,  sum(s.stock) as sd, count((case when s.stock=0 then null else 1 end)) as presence  from (select v.id,v.date,u.pv from (select pv.id as pv , max(v.date) as date from point_vente pv join visite v  on pv.id=v.point_vente_id and v.date>=:startDate and v.date<=:endDate and pv.region=:region group by  pv.id order by pv.id) as u  join  visite v on (u.pv=v.point_vente_id and u.date=v.date) ) as v join situation s on v.id=s.visite_id join produit p on p.id=s.produit_id group by p.id,v.pv) situation group by id ) situation join produit p on p.id=situation.id;'  : 'select p.id,situation.sd,situation.presence,p.dossier from (select id,  sum(sd) as sd, sum(presence) as presence from (select v.pv, p.id,  sum(s.stock) as sd, count((case when s.stock=0 then null else 1 end)) as presence  from (select v.id,v.date,u.pv from (select pv.id as pv , max(v.date) as date from point_vente pv join visite v  on pv.id=v.point_vente_id and v.date>=:startDate and v.date<=:endDate  group by  pv.id order by pv.id) as u  join  visite v on (u.pv=v.point_vente_id and u.date=v.date) ) as v join situation s on v.id=s.visite_id join produit p on p.id=s.produit_id group by p.id,v.pv) situation group by id ) situation join produit p on p.id=situation.id;'; 
  $statement = $em->getConnection()->prepare($RAW_QUERY);
        if($region!=null){
   $statement->bindValue('region', $region);
          }
    $startDate=new \DateTime($startDate);
    $endDate=new \DateTime($endDate);

     $statement->bindValue('startDate', $startDate->format('Y-m-d'));
     $statement->bindValue('endDate',  $endDate->format('Y-m-d'));
     $statement->execute();

      return  $result = $statement->fetchAll();
  } 
}
