<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SituationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationRepository extends EntityRepository
{

	public function stockParProduit ($region=null, $startDate=null, $endDate=null){

        $qb = $this->createQueryBuilder('s')->join('s.produit','p')->join('s.visite','v')->join('v.pointVente','pv');
        if($region!=null){
           $qb->where('pv.ville=:ville')
          ->setParameter('ville', $region);
          }
          if($startDate!=null){
           $qb->andWhere('v.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('v.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }
          $qb->addGroupBy('s.id');
          $qb->addSelect('sum(s.stock) as stock');
          $qb->addSelect('avg(s.mvj) as mvj');
          $qb->addSelect('avg(s.ecl) as ecl');   
          return $qb->getQuery()->getResult();
     
  }

}
