<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteRepository extends EntityRepository
{

   public function findList($region=null, $startDate=null, $endDate=null){
         $qb = $this->createQueryBuilder('v')->join('v.client','c');
        if($region!=null){
           $qb->where('c.ville=:ville')
          ->setParameter('ville', $region);
          }
      if($startDate!=null){
           $qb->andWhere('v.date>=:startDate')
          ->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('v.date<=:endDate')
          ->setParameter('endDate',new \DateTime($endDate));
          }          
          return $qb->getQuery()->getArrayResult();
  }   
}
