parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-23-21-171-249.compute-1.amazonaws.com
    database_port: 5432
    database_name: datmbd6r3quaot
    database_user: svogvyoqambrxo
    database_password: 9b2d7ca23d1c28950118e61deab7d3f82e17d14bbb1695e953a67c3123572692
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
