parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-54-235-84-244.compute-1.amazonaws.com
    database_port: 5432
    database_name: d4g4b9bbdi6iag
    database_user: vpsahgmmcqlpvx
    database_password: 326794d8c3b73740644b32672e7196e2d6675ccb520e1e037ab5b994690209b0
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
