parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-54-246-117-62.eu-west-1.compute.amazonaws.com
    database_port: 5432
    database_name: d5rrvs2ksmnovu
    database_user: aayhyxlqlpksbs
    database_password: 06dfd88d229391fc3c092510476ae2678799055e7334f71f41e8c6d47383b997
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
