parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-54-163-240-54.compute-1.amazonaws.com
    database_port: 5432
    database_name: dbh3f629fadbss
    database_user: tgeedmhhwfdzxj
    database_password: 9ad7438a61a7478d2f8e52ad163631242b03601037160cb51c34a6b941a15224
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
