parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-23-23-111-171.compute-1.amazonaws.com
    database_port: 5432
    database_name: d7piji7ccsuqki
    database_user: wcabmyovxsroof
    database_password: f0e13ac4c539c18d52ca8a08211261e0359a9a6677a3cda4806c2cec7571abab
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
