
homepage:
    path:     /
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET

set_periode:
    path:     /set/periode
    defaults: { _controller: "AppBundle:App:setPeriode" }
    methods:  POST

load_default:
    path:     /load/default
    defaults: { _controller: "AppBundle:App:loadDefault" }
    methods:  GET

load_default_visite:
    path:     /load/default/visite
    defaults: { _controller: "AppBundle:App:loadDefaultVisite" }
    methods:  GET

load_default_synchro:
    path:     /load/default/synchro
    defaults: { _controller: "AppBundle:App:loadDefaultSynchro" }
    methods:  GET

load_default_produit:
    path:     /load/default/produit
    defaults: { _controller: "AppBundle:App:loadDefaultProduit" }
    methods:  GET

load_default_etape:
    path:     /load/default/etape
    defaults: { _controller: "AppBundle:App:loadDefaultEtape" }
    methods:  GET
    

user_homepage:
    path:     /v1/home
    defaults: { _controller: "AppBundle:App:accueil" }
    methods:  GET

app_admin:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /v1

      
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile