app:
    resource: "@AppBundle/Controller/"
    type:      annotation
  
app_admin:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
       
login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout