
homepage:
    path:     /
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET
mobileapp:
    path:     /apk
    defaults: { _controller: "AppBundle:Mobile:apk" }
    methods:  GET


user_homepage:
    path:     /v1/home
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET

help:
    path:     /v1/mobile/{topic}/help
    defaults: { _controller: "AppBundle:App:help" }
    methods:  GET

cgu:
    path:     /v1/mobile/cgu
    defaults: { _controller: "AppBundle:App:cgu" }
    methods:  GET


app_admin:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /v1

      
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
