# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     my_service_connection: default
     logout.target: /

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     resto.security.authentication_success_handler:
           class: AppBundle\Handler\AuthenticationSuccessHandler

     resto.security.authentication_failure_handler:
           class: AppBundle\Handler\AuthenticationFailureHandler

     resto.security.authentication_entry_point:
           class: AppBundle\Handler\AuthenticationEntryPoint

     resto.security.remember_me:
           class: Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider
           arguments:  [@doctrine.dbal.default_connection]

     resto.logout_success_handler:
           class: AppBundle\Handler\LogoutSuccessHandler
           arguments:  [@doctrine.dbal.default_connection, %logout.target%]