# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     my_service_connection: default
     logout.target: /

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
      app.form.registration:
                class: AppBundle\Form\RegistrationType
                tags:
                    - { name: form.type, alias: app_user_registration }

      app.twig_extension:
                class: AppBundle\Twig\AppExtension
                public: false
                tags:
                    - { name: twig.extension }
      create_listener:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager"]
          tags:
            - { name: kernel.event_listener, event: object.created, method: onObjetCreated }