# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     my_service_connection: default
     logout.target: /

services:
      http_request_maker:
         class: AppBundle\Service\HttpRequestMaker
      
      payment_service:
         class: AppBundle\Service\PayementService

      
      previsonal_produit:
          class: AppBundle\Service\PrevisonalProduit
          arguments: ["@doctrine.orm.entity_manager"]

      previsonal_client:
          class: AppBundle\Service\PrevisonalClient
          arguments: ["@doctrine.orm.entity_manager", "@previsonal_produit"]