Pwm\AdminBundle\Entity\Price:
    exclusion_policy: none
    properties:
        starter:
             groups: ['price', 'session','full','abonnement']             
        standard:
             groups: ['price', 'session','full','abonnement']
        premium:
             groups: ['price', 'session','full','abonnement']
        starterDesc:
             groups: ['price', 'session','full','abonnement']            
        standardDesc:
             groups: ['price', 'session','full','abonnement']
        premiumDesc:
             groups: ['price', 'session','full','abonnement']
        starterDelay:
             groups: ['price', 'session','full','abonnement']            
        standardDelay:
             groups: ['price', 'session','full','abonnement']
        premiumDelay:
             groups: ['price', 'session','full','abonnement']