Pwm\AdminBundle\Entity\Ressource:
    exclusion_policy: none
    properties:
        id:
            groups: ['matiere','ressource', 'full']
        description:
             groups: ['matiere','ressource', 'full']
        detail1:
             groups: ['ressource', 'full']    
        detail2:
             groups: ['ressource', 'full']  
        detail3:
             groups: ['ressource', 'full']  
        style:
             groups: ['ressource', 'full']    
        size:
             groups: ['ressource', 'full']  
        detail4:
             groups: ['ressource', 'full']               
        nom:
             groups: ['matiere','ressource', 'full'] 
        label:
             groups: ['ressource', 'full']              
        url:
             groups: ['full']   
        imageUrl:
             groups: ['ressource', 'full']  
        paymentUrl:
             groups: ['ressource', 'full']                                                                                                 
        price:
             groups: ['matiere','full']
