Pwm\AdminBundle\Entity\Analyse:
    exclusion_policy: none
    properties:
        id:
            groups: ['analyse', 'full']
        time:
             groups: ['analyse', 'full']
        failedNb:
             groups: ['analyse', 'full']             
        trueNb:
             groups: ['analyse', 'full']
        dememe:
             groups: ['analyse', 'full']
        rang:
             groups: ['analyse', 'full']             
        sup10:
             groups: ['analyse', 'full']
        firstNote:
             groups: ['analyse', 'full']
        note:
             groups: ['analyse', 'full']             
        objectif:
             groups: ['analyse', 'full']
        programme:
             groups: ['analyse', 'full']
        evalues:
             groups: ['analyse', 'full']