user_index_json:
    path:     /vendeur/json
    defaults: { _controller: "AppBundle:MobileUser:indexJson" }
    methods:  [GET, POST]


user_new_json:
    path:     /register/new/json
    defaults: { _controller: "AppBundle:MobileUser:registerJson" }
    methods:  [GET, POST]



user_show_json:
    path:     /user/{id}/show/json
    defaults: { _controller: "AppBundle:MobileUser:showJson" }
    methods:  GET

user_edit_json:
    path:      /user/{id}/edit/json
    defaults: { _controller: "AppBundle:MobileUser:editJson" }
    methods:  [GET, POST,PUT]

create_token:
    path:      /token/new/json
    defaults: { _controller: "AppBundle:AuthToken:postAuthTokens" }
    methods:  POST

create_credentials:
    path:      /credential/new/json
    defaults: { _controller: "AppBundle:AuthToken:postCredential" }
    methods:  POST

check_token:
    path:      /token/check/json
    defaults: { _controller: "AppBundle:AuthToken:checkAuthTokens" }
    methods:  POST  

token_show_json:
    path:     /token/{id}/show/json
    defaults: { _controller: "AppBundle:AuthToken:showJson" }
    methods:  GET

create_request:
    path:      /request/new/json
    defaults: { _controller: "AppBundle:MobileUser:newJson" }
    methods:  POST  

delete_request:
    path:      /request/{id}/delete/json
    defaults: { _controller: "AppBundle:MobileUser:deleteRequestJson" }
    methods:   DELETE

accept_request:
    path:      /request/{id}/accept/json
    defaults: { _controller: "AppBundle:MobileUser:acceptRequestJson" }
    methods:   DELETE

refuse_request:
    path:      /request/{id}/refuse/json
    defaults: { _controller: "AppBundle:MobileUser:deleteRequestJson" }
    methods:   DELETE

delete_user:
    path:      /vendeur/{id}/delete/json
    defaults: { _controller: "AppBundle:MobileUser:deleteUserJson" }
    methods:  DELETE