analyse_index:
    path:     /
    defaults: { _controller: "AppBundle:Analyse:index" }
    methods:  GET

analyse_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Analyse:show" }
    methods:  GET

analyse_new:
    path:     /new
    defaults: { _controller: "AppBundle:Analyse:new" }
    methods:  [GET, POST]

analyse_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Analyse:edit" }
    methods:  [GET, POST]

analyse_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Analyse:delete" }
    methods:  DELETE
