article_index:
    path:     /
    defaults: { _controller: "AppBundle:Article:index" }
    methods:  GET

article_valid:
    path:     /{id}/valid
    defaults: { _controller: "AppBundle:Article:valide" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Article:show" }
    methods:  GET

article_show_from_mobile:
    path:     /{id}/show/from/mobile
    defaults: { _controller: "AppBundle:Article:showFromMobile" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "AppBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Article:delete" }
    methods:  DELETE
