campagne_index:
    path:     /
    defaults: { _controller: "AppBundle:Campagne:index" }
    methods:  GET

campagne_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Campagne:show" }
    methods:  GET

campagne_new:
    path:     /new
    defaults: { _controller: "AppBundle:Campagne:new" }
    methods:  [GET, POST]

campagne_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Campagne:edit" }
    methods:  [GET, POST]

campagne_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Campagne:delete" }
    methods:  DELETE
