campagne_index:
    path:     /
    defaults: { _controller: "AppBundle:Campagne:index" }
    methods:  GET

campagnes_by_pays:
    path:     /campagnes/{pays}
    defaults: { _controller: "AppBundle:Campagne:camapgnesByContry" }
    methods:  GET

campagne_show:
    path:     /see/{id}/show
    defaults: { _controller: "AppBundle:Campagne:show" }
    methods:  GET

campagne_new:
    path:     /new
    defaults: { _controller: "AppBundle:Campagne:new" }
    methods:  [GET, POST]

campagne_edit:
    path:     /see/{id}/edit
    defaults: { _controller: "AppBundle:Campagne:edit" }
    methods:  [GET, POST]


campagne_edit_one:
    path:     /one/{field}/{id}/edit
    defaults: { _controller: "AppBundle:Campagne:editOne" }
    methods:  [GET, POST]

campagne_add_repport:
    path:     /one/add/{id}/repport
    defaults: { _controller: "AppBundle:Campagne:addRapport" }
    methods:  [GET, POST]


campagne_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Campagne:delete" }
    methods:  DELETE
