candidat_index:
    path:     /
    defaults: { _controller: "AppBundle:Candidat:index" }
    methods:  GET

candidat_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Candidat:show" }
    methods:  GET

candidat_new:
    path:     /new
    defaults: { _controller: "AppBundle:Candidat:new" }
    methods:  [GET, POST]

candidat_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Candidat:edit" }
    methods:  [GET, POST]

candidat_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Candidat:delete" }
    methods:  DELETE
