chargement_index:
    path:     /{user}/{date}
    defaults: { _controller: "AppBundle:Chargement:index" }
    methods:  GET

chargement_index_all:
    path:     /{user}
    defaults: { _controller: "AppBundle:Chargement:index" }
    methods:  GET

chargement_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Chargement:show" }
    methods:  GET

chargement_new:
    path:     /new/{id}
    defaults: { _controller: "AppBundle:Chargement:new" }
    methods:  [GET, POST]

chargement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Chargement:edit" }
    methods:  [GET, POST]

chargement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Chargement:delete" }
    methods:  DELETE
