chargement_index:
    path:     /{user}/{date}
    defaults: { _controller: "AppBundle:Chargement:index" }
    methods:  GET

chargement_index_all:
    path:     /{user}
    defaults: { _controller: "AppBundle:Chargement:index" }
    methods:  GET

chargement_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Chargement:show" }
    methods:  GET

chargement_new:
    path:     /new/{id}/{prod}
    defaults: { _controller: "AppBundle:Chargement:new" }
    methods:  [GET, POST]

chargement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Chargement:edit" }
    methods:  [GET, POST]

chargement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Chargement:delete" }
    methods:  DELETE



chargement_all_page:
    path:     /web/all/page
    defaults: { _controller: "AppBundle:Chargement:allPage" }
    methods:  GET

chargement_all_json:
    path:     /web/all/json
    defaults: { _controller: "AppBundle:Chargement:allJson" }
    methods:  GET