client_index:
    path:     /
    defaults: { _controller: "AppBundle:Client:index" }
    methods:  GET

client_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Client:show" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "AppBundle:Client:new" }
    methods:  [GET, POST]

client_new_super:
    path:     /new/super
    defaults: { _controller: "AppBundle:Client:newSuper" }
    methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Client:edit" }
    methods:  [GET, POST,PUT]

client_changePasswordAction:
    path:     /{id}/change/passeword
    defaults: { _controller: "AppBundle:Client:changePassword" }
    methods:  [GET, POST,PUT]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Client:delete" }
    methods:  DELETE
