commandeproduit_index:
    path:     /{id}
    defaults: { _controller: "AppBundle:CommandeProduit:index" }
    methods:  GET

commandeproduit_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CommandeProduit:show" }
    methods:  GET

commandeproduit_new:
    path:     /new
    defaults: { _controller: "AppBundle:CommandeProduit:new" }
    methods:  [GET, POST]

commandeproduit_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CommandeProduit:edit" }
    methods:  [GET, POST]

commandeproduit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CommandeProduit:delete" }
    methods:  DELETE
