paiment_index:
    path:     /
    defaults: { _controller: "AppBundle:Abonnement:index" }
    methods:  GET

paiment_show:
    path:     /{id}/show/json
    defaults: { _controller: "AppBundle:Abonnement:showJson" }
    methods:  GET

paiment_confirm:
    path:     /{id}/confirm/json
    defaults: { _controller: "AppBundle:Abonnement:confirm" }
    methods: [GET, POST]

paiment_cancel:
    path:     /{id}/cancel/json
    defaults: { _controller: "AppBundle:Abonnement:cancel" }
    methods:  GET


paiment_new:
    path:     /new/json
    defaults: { _controller: "AppBundle:Abonnement:init" }
    methods:  [GET, POST]