commandeclient_index:
    path:     /{user}
    defaults: { _controller: "AppBundle:CommandeClient:index" }
    methods:  GET

commandeclient_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CommandeClient:show" }
    methods:  GET

commandeclient_new:
    path:     /new/{point}/{user}
    defaults: { _controller: "AppBundle:CommandeClient:new" }
    methods:  [GET, POST]

commandeclient_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:CommandeClient:edit" }
    methods:  [GET, POST]

commandeclient_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CommandeClient:delete" }
    methods:  DELETE
