concours_index:
    path:     /
    defaults: { _controller: "AppBundle:Concours:index" }
    methods:  GET

concours_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Concours:show" }
    methods:  GET

concours_new_from:
    path:     /new/from/programme
    defaults: { _controller: "AppBundle:Concours:newFromProgrmme" }
    methods:  [GET, POST]

concours_new:
    path:     /new
    defaults: { _controller: "AppBundle:Concours:new" }
    methods:  [GET, POST]

concours_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Concours:edit" }
    methods:  [GET, POST]

concours_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Concours:delete" }
    methods:  DELETE
