etape_index:
    path:     /{id}/index
    defaults: { _controller: "AppBundle:Etape:index" }
    methods:  GET

etape_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Etape:show" }
    methods:  GET

etape_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:Etape:new" }
    methods:  [GET, POST]

etape_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Etape:edit" }
    methods:  [GET, POST]

etape_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Etape:delete" }
    methods:  DELETE
