etape_index:
    path:     /
    defaults: { _controller: "AppBundle:Etape:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Etape:show" }
    methods:  GET



