explication_index:
    path:     /
    defaults: { _controller: "AppBundle:Explication:index" }
    methods:  GET

explication_show:
    path:     /{id}/show/{question}/{content}
    defaults: { _controller: "AppBundle:Explication:show" , question:0, content:0 }
    methods:  GET

explication_new:
    path:     /new/{question}/{content}
    defaults: { _controller: "AppBundle:Explication:new", question:0, content:0 }
    methods:  [GET, POST]

explication_edit:
    path:     /{id}/edit/{question}/{content}
    defaults: { _controller: "AppBundle:Explication:edit", question:0, content:0  }
    methods:  [GET, POST]

explication_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Explication:delete" }
    methods:  DELETE
