commende_index_json:
    path:     /commande/json
    defaults: { _controller: "AppBundle:Commende:indexJson"}
    methods:  GET

commende_show_json:
    path:     /commande/{id}/show/json
    defaults: { _controller: "AppBundle:Commende:showJson" }
    methods:  GET

commende_new_json:
    path:     /commande/new/json
    defaults: { _controller: "AppBundle:Commende:newJson" }
    methods:  [GET, POST]

commende_edit_json:
    path:      /commande/{id}/edit/json
    defaults: { _controller: "AppBundle:Commende:editJson" }
    methods:  [GET, POST]

commende_delete_json:
    path:      /commande/{id}/delete/json
    defaults: { _controller: "AppBundle:Commende:deleteJson" }
    methods:  DELETE

produit_index_json:
    path:     /produit/json
    defaults: { _controller: "AppBundle:Produit:indexJson" }
    methods:  GET

point_vente_index_json:
    path:     /pointvente/json
    defaults: { _controller: "AppBundle:PointVente:indexJson" }
    methods:  GET

commende_show_json:
    path:     /pointvente/{id}/show/json
    defaults: { _controller: "AppBundle:PointVente:showJson" }
    methods:  GET
