article_index_json:
    path:     /article/json
    defaults: { _controller: "AppBundle:Article:jsonIndex" }
    methods:  GET

concours_index_json:
    path:     /concours/json
    defaults: { _controller: "AppBundle:Programme:jsonIndex" }
    methods:  GET

concours_show_json:
    path:     /concours/{id}/json
    defaults: { _controller: "AppBundle:Programme:showJson" }
    methods:  GET

matiere_index_json:
    path:     /matiere/{id}/json
    defaults: { _controller: "AppBundle:Matiere:jsonIndex" }
    methods:  GET

partie_index_json:
    path:     /partie/{id}/json
    defaults: { _controller: "AppBundle:Partie:jsonIndex" }
    methods:  GET

question_index_json:
    path:     /question/{id}/json
    defaults: { _controller: "AppBundle:Question:jsonIndex" }
    methods:  GET

abonnement_index_json:
    path:     /abonnement/{studentId}/json
    defaults: { _controller: "AppBundle:Abonnement:indexJson"}
    methods:  GET

abonnement_new_json:
    path:     /abonnement/{id}/new/json
    defaults: { _controller: "AppBundle:Abonnement:newJson" ,id:0}
    methods:  [GET,POST]
  
abonnement_show_json:
    path:     /abonnement/{studentId}/{id}/json
    defaults: { _controller: "AppBundle:Abonnement:showJson"}
    methods:  [GET,POST]  
