article_index_json:
    path:     /article/{start}/json
    defaults: { _controller: "AppBundle:Article:jsonIndex", start:0 }
    methods:  GET

programme_index_json:
    path:     /concours/{start}/json
    defaults: { _controller: "AppBundle:Programme:jsonIndex", start:0}
    methods:  GET

programme_show_json:
    path:     /concours/{id}/show/json
    defaults: { _controller: "AppBundle:Programme:showJson" }
    methods:  GET

session_index_json:
    path:     /session/{start}/json
    defaults: { _controller: "AppBundle:Session:jsonIndex", start:0}
    methods:  GET

session_show_json:
    path:     /session/{id}/show/json
    defaults: { _controller: "AppBundle:Session:showJson" }
    methods:  GET

session_follow_json:
    path:     /session/{session}/{info}/follows/json
    defaults: { _controller: "AppBundle:Session:follows" }
    methods:  GET


article_show_json:
    path:     /article/{id}/show/json
    defaults: { _controller: "AppBundle:Article:showJson" }
    methods:  GET

matiere_index_json:
    path:     /matiere/{id}/json
    defaults: { _controller: "AppBundle:Matiere:jsonIndex" }
    methods:  GET

partie_index_json:
    path:     /partie/{id}/json
    defaults: { _controller: "AppBundle:Partie:jsonIndex" }
    methods:  GET

question_index_json:
    path:     /question/{id}/json
    defaults: { _controller: "AppBundle:Question:jsonIndex" }
    methods:  GET
