article_index_json:
    path:     /article/{start}/json
    defaults: { _controller: "AppBundle:Article:jsonIndex",, start:0 }
    methods:  GET

concours_index_json:
    path:     /concours/{start}/json
    defaults: { _controller: "AppBundle:Programme:jsonIndex", start:0}
    methods:  GET

concours_show_json:
    path:     /concours/{id}/show/json
    defaults: { _controller: "AppBundle:Programme:showJson" }
    methods:  GET

matiere_index_json:
    path:     /matiere/{id}/json
    defaults: { _controller: "AppBundle:Matiere:jsonIndex" }
    methods:  GET

partie_index_json:
    path:     /partie/{id}/json
    defaults: { _controller: "AppBundle:Partie:jsonIndex" }
    methods:  GET

question_index_json:
    path:     /question/{id}/json
    defaults: { _controller: "AppBundle:Question:jsonIndex" }
    methods:  GET

abonnement_index_json:
    path:     /abonnement/{studentId}/json
    defaults: { _controller: "AppBundle:Abonnement:indexJson"}
    methods:  GET

abonnement_new_json:
    path:     /abonnement/{id}/new/json
    defaults: { _controller: "AppBundle:Abonnement:newJson" ,id:0}
    methods:  [GET,POST]
  
abonnement_show_json:
    path:     /abonnement/{studentId}/{id}/json
    defaults: { _controller: "AppBundle:Abonnement:showJson"}
    methods:  [GET,POST] 

candidat_new_json:
    path:     /candidat/{studentId}/new/json
    defaults: { _controller: "AppBundle:Candidat:newJson" }
    methods:  [GET,POST]
  
candidat_show_json:
    path:     /candidat/{studentId}/json
    defaults: { _controller: "AppBundle:Candidat:showJson"}
    methods:  [GET,POST] 

info_new_json:
    path:     /info/{studentId}/new/json
    defaults: { _controller: "AppBundle:Info:newJson" }
    methods:  [GET,POST]
 
info_edit_picture:
    path:     /info/{id}/picture
    defaults: { _controller: "AppBundle:Info:editPicture" }
    methods:  [GET,POST] 

info_show_json:
    path:     /info/{studentId}/json
    defaults: { _controller: "AppBundle:Info:showJson"}
    methods:  [GET,POST] 


analyse_new_json:
    path:     /analyse/{studentId}/{concours}/{matiere}/{partie}/new/json
    defaults: { _controller: "AppBundle:Analyse:newJson" ,matiere:0,partie:0}
    methods:  [GET,POST]
  
analyse_show_json:
    path:     /analyse/{studentId}/{concours}/{matiere}/{partie}/json
    defaults: { _controller: "AppBundle:Analyse:showJson",matiere:0,partie:0}
    methods:  [GET,POST]      
