journee_index:
    path:     /{id}/{date}
    defaults: { _controller: "AppBundle:Journee:index", id:0, date: null }
    methods:  GET

journee_index:
    path:     /{id}
    defaults: { _controller: "AppBundle:Journee:index", id:0 }
    methods:  GET

journee_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Journee:show" }
    methods:  GET

journee_new:
    path:     /new/{id}
    defaults: { _controller: "AppBundle:Journee:new" }
    methods:  [GET, POST]

journee_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Journee:edit" }
    methods:  [GET, POST]

journee_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Journee:delete" }
    methods:  DELETE
