matiere_index:
    path:     /{id}/list
    defaults: { _controller: "AppBundle:Matiere:index" }
    methods:  GET
    schemes:    [https]

matiere_show_from_mobile:
    path:     /{id}/show/from/mobile
    defaults: { _controller: "AppBundle:Objectif:index" }
    methods:  GET
    schemes:    [https]

matiere_show_from_mobile2:
    path:     /{id}/ressources
    defaults: { _controller: "AppBundle:Objectif:index" }
    methods:  GET
    schemes:    [https]

matiere_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Matiere:show" }
    methods:  GET
    schemes:    [https]   
matiere_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:Matiere:new" }
    methods:  [GET, POST]
    schemes:    [https]
matiere_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Matiere:edit" }
    methods:  [GET, POST]
    schemes:    [https]
    
matiere_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Matiere:delete" }
    methods:  DELETE
    schemes:    [https]