matiere_index:
    path:     /{id}/list/{session}
    defaults: { _controller: "AppBundle:Matiere:index","session":0}
    methods:  GET

matiere_show_from_mobile:
    path:     /{id}/show/from/mobile
    defaults: { _controller: "AppBundle:Objectif:index" }
    methods:  GET

matiere_show_from_mobile2:
    path:     /{id}/ressources
    defaults: { _controller: "AppBundle:Objectif:index" }
    methods:  GET

matiere_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Matiere:show" }
    methods:  GET

matiere_new:
    path:     /{id}/new/{session}
    defaults: { _controller: "AppBundle:Matiere:new","session":0 }
    methods:  [GET, POST]

matiere_reindex:
    path:     /reindex
    defaults: { _controller: "AppBundle:Matiere:reindex" }
    methods:  [GET, POST]

matiere_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Matiere:edit" }
    methods:  [GET, POST]

matiere_copy:
    path:     /{id}/copy
    defaults: { _controller: "AppBundle:Matiere:copy" }
    methods:  [GET, POST]


matiere_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Matiere:delete" }
    methods:  DELETE
