poin_ventes:
    path:      /points/ventes
    defaults: { _controller: "AppBundle:Mobile:pointVentes" }
    methods:  GET

produits:
    path:      /produits
    defaults: { _controller: "AppBundle:Mobile:produits" }
    methods:  GET

create_point_ventes:
    path:      /create/points/ventes
    defaults: { _controller: "AppBundle:Mobile:createPointVentes" }
    methods:  POST

create_visites:
    path:      /create/visites
    defaults: { _controller: "AppBundle:Mobile:createVisites" }
    methods:  POST

create_etatpes:
    path:      /create/etapes
    defaults: { _controller: "AppBundle:Mobile:createEtapes" }
    methods:  POST 

create_token:
    path:      /create/auth-token
    defaults: { _controller: "AppBundle:Mobile:postAuthTokens" }
    methods:  POST

