objectif_index:
    path:     /{id}/list
    defaults: { _controller: "AppBundle:Objectif:index" }
    methods:  GET
    schemes:    [https]

objectif_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Objectif:show" }
    methods:  GET
    schemes:    [https]

objectif_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:Objectif:new" }
    methods:  [GET, POST]
    schemes:    [https]

objectif_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Objectif:edit" }
    methods:  [GET, POST]
    schemes:    [https]
    
objectif_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Objectif:delete" }
    methods:  DELETE
    schemes:    [https]