partie_index:
    path:     /{id}/list
    defaults: { _controller: "AppBundle:Partie:index", id:0 }
    methods:  GET


partie_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Partie:show" }
    methods:  GET

partie_difucult:
    path:     /{id}/dificult/questions
    defaults: { _controller: "AppBundle:Partie:getDificultQuestions" }
    methods:  GET

partie_attr:
    path:     /{id}/attr
    defaults: { _controller: "AppBundle:Partie:attr" }
    methods:  [GET, POST]

partie_enable:
    path:     /{id}/enable
    defaults: { _controller: "AppBundle:Partie:enable" }
    methods:  [GET, POST]

partie_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:Partie:new" }
    methods:  [GET, POST]

partie_edit:
    path:     /{id}/edit/{matiere}
    defaults: { _controller: "AppBundle:Partie:edit" }
    methods:  [GET, POST]

partie_delete:
    path:     /{id}/delete/{matiere}
    defaults: { _controller: "AppBundle:Partie:delete" }
    methods:  DELETE

partie_is_avalable:
    path:     /{id}/is/avalable
    defaults: { _controller: "AppBundle:Partie:isAvalable" }
    methods:  GET