phoning_index:
    path:     /
    defaults: { _controller: "AppBundle:Phoning:index" }
    methods:  GET

phoning_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Phoning:show" }
    methods:  GET

phoning_new:
    path:     /new
    defaults: { _controller: "AppBundle:Phoning:new" }
    methods:  [GET, POST]

phoning_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Phoning:edit" }
    methods:  [GET, POST]

phoning_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Phoning:delete" }
    methods:  DELETE
