plat_index:
    path:     /{menu}/list
    defaults: { _controller: "AppBundle:Plat:index","menu":0 }
    methods:  GET

plat_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Plat:show" }
    methods:  GET

plat_new:
    path:     /new
    defaults: { _controller: "AppBundle:Plat:new" }
    methods:  [GET, POST]

plat_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Plat:edit" }
    methods:  [GET, POST]

plat_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Plat:delete" }
    methods:  DELETE
