pointvente_index:
    path:     /
    defaults: { _controller: "AppBundle:PointVente:index" }
    methods:  GET

pointvente_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PointVente:show" }
    methods:  GET

pointvente_new:
    path:     /new/{id}
    defaults: { _controller: "AppBundle:PointVente:new" }
    methods:  [GET, POST]

pointvente_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:PointVente:edit" }
    methods:  [GET, POST]

pointvente_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:PointVente:delete" }
    methods:  DELETE

pointvente_all_page:
    path:     /web/all/page
    defaults: { _controller: "AppBundle:PointVente:allPage" }
    methods:  GET

pointvente_all_json:
    path:     /web/all/json
    defaults: { _controller: "AppBundle:PointVente:allJson" }
    methods:  GET