pointvente_index:
    path:     /
    defaults: { _controller: "AppBundle:PointVente:index" }
    methods:  GET

pointvente_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PointVente:show" }
    methods:  GET

pointvente_eligibles:
    path:     /{note}/eligibles
    defaults: { _controller: "AppBundle:PointVente:eligibles", note:0 }
    methods:  GET

pointvente_map:
    path:     /geo
    defaults: { _controller: "AppBundle:PointVente:map" }
    methods:  GET

