programme_index:
    path:     /
    defaults: { _controller: "AppBundle:Programme:index" }
    methods:  GET


programme_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Programme:show" }
    methods:  GET

programme_new:
    path:     /new
    defaults: { _controller: "AppBundle:Programme:new" }
    methods:  [GET, POST]

programme_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Programme:edit" }
    methods:  [GET, POST]

programme_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Programme:delete" }
    methods:  DELETE

