concours_index:
    path:     /
    defaults: { _controller: "AppBundle:Programme:index" }
    methods:  GET


concours_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Programme:show" }
    methods:  GET

concours_new:
    path:     /new
    defaults: { _controller: "AppBundle:Programme:new" }
    methods:  [GET, POST]

concours_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Programme:edit" }
    methods:  [GET, POST]

concours_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Programme:delete" }
    methods:  DELETE
