programme_index:
    path:     /
    defaults: { _controller: "AppBundle:Programme:index" }
    methods:  GET


programme_show:
    path:     /{id}/show/{session}
    defaults: { _controller: "AppBundle:Programme:show","session":0 }
    methods:  GET

programme_new:
    path:     /new/{session}
    defaults: { _controller: "AppBundle:Programme:new" ,"session":0}
    methods:  [GET, POST]

programme_edit:
    path:     /{id}/edit/{session}
    defaults: { _controller: "AppBundle:Programme:edit","session":0}
    methods:  [GET, POST]

programme_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Programme:delete" }
    methods:  DELETE

