question_index:
    path:     /{id}/list
    defaults: { _controller: "AppBundle:Question:index" }
    methods:  GET


question_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Question:show" }
    methods:  GET

question_show_from_mobile:
    path:     /{id}/show/from/mobile
    defaults: { _controller: "AppBundle:Question:showFromMobile" }
    methods:  GET

question_valid:
    path:     /{id}/valid
    defaults: { _controller: "AppBundle:Question:valide" }
    methods:  GET

question_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:Question:new" }
    methods:  [GET, POST]

question_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Question:edit" }
    methods:  [GET, POST]

question_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Question:delete" }
    methods:  DELETE
