rapport_index:
    path:     /rapport/
    defaults: { _controller: "AppBundle:Rapport:index" }
    methods:  GET

rapport_index_json:
    path:     /rapport/json
    defaults: { _controller: "AppBundle:Rapport:indexJson" }
    methods:  GET

stats_index_json: 
    path:     /stat/json
    defaults: { _controller: "AppBundle:Rapport:statsJson" }
    methods:  GET

map_index_json: 
    path:     /map/json
    defaults: { _controller: "AppBundle:Rapport:mapJson" }
    methods:  GET

prevision_index_json: 
    path:     /prevision/json
    defaults: { _controller: "AppBundle:Rapport:previsionsJson" }
    methods:  GET


rapport_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Rapport:show" }
    methods:  GET

rapport_show_json:
    path:     /stat/{id}/show/json
    defaults: { _controller: "AppBundle:Rapport:statsJson" }
    methods:  GET

