secteur_index_json:
    path:     /json
    defaults: { _controller: "AppBundle:Secteur:indexJson" }
    methods:  GET

secteur_show_json:
    path:     /{id}/show/json
    defaults: { _controller: "AppBundle:Secteur:showJson" }
    methods:  GET

secteur_new_json:
    path:     /new/json
    defaults: { _controller: "AppBundle:Secteur:newJson" }
    methods:  [GET, POST]

secteur_edit_json:
    path:     /{id}/edit/json
    defaults: { _controller: "AppBundle:Secteur:editJson" }
    methods:  [GET, POST,PUT]

secteur_delete_json:
    path:     /{id}/delete/json
    defaults: { _controller: "AppBundle:Secteur:deleteJson" }
    methods:  DELETE
