session_index:
    path:     /{id}/{all}/list
    defaults: { _controller: "AppBundle:Session:index","id":0 ,"all":0 }
    methods:  GET
    

session_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Session:show" }
    methods:  GET

session_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:Session:new" }
    methods:  [GET, POST]
    
session_attr:
    path:     /{id}/attr
    defaults: { _controller: "AppBundle:Session:attr" }
    methods:  [GET, POST]

session_whatsapp:
    path:     /{id}/whatsapp
    defaults: { _controller: "AppBundle:Session:whatsapp" }
    methods:  [GET, POST]


session_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Session:edit" }
    methods:  [GET, POST]

session_analyse:
    path:     /{id}/analyse
    defaults: { _controller: "AdminBundle:Analyse:analyse" }
    methods:  [GET, POST]



session_decrire:
    path:     /{id}/decrire
    defaults: { _controller: "AppBundle:Session:decrire" }
    methods:  [GET, POST]

session_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Session:delete" }
    methods:  DELETE

session_show_from_mobile:
    path:     /{id}/show/from/mobile
    defaults: { _controller: "AppBundle:Session:showFromMobile" }
    methods:  GET