souscripteur_index:
    path:     /
    defaults: { _controller: "AppBundle:Souscripteur:index" }
    methods:  GET

souscripteur_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Souscripteur:show" }
    methods:  GET

souscripteur_new:
    path:     /new
    defaults: { _controller: "AppBundle:Souscripteur:new" }
    methods:  [GET, POST]

souscripteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Souscripteur:edit" }
    methods:  [GET, POST]

souscripteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Souscripteur:delete" }
    methods:  DELETE
