telephone_index:
    path:     /
    defaults: { _controller: "AppBundle:Telephone:index" }
    methods:  GET

telephone_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Telephone:show" }
    methods:  GET



