visite_par_pdv:
    path:     /pdv
    defaults: { _controller: "AppBundle:Visite:visitesParPDV" }
    methods:  GET

visites:
    path:     /
    defaults: { _controller: "AppBundle:Visite:visites" }
    methods:  GET

visite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Visite:show" }
    methods:  GET



