visite_par_pdv:
    path:     /pdv
    defaults: { _controller: "AppBundle:Visite:visitesParPDV" }
    methods:  GET

visite_par_pdv_excel:
    path:     /pdv/excel
    defaults: { _controller: "AppBundle:Visite:derniereVisiteExcel" }
    methods:  GET

visites:
    path:     /
    defaults: { _controller: "AppBundle:Visite:visites" }
    methods:  GET
visites_excel:
    path:     /excel
    defaults: { _controller: "AppBundle:Visite:visitesExcel" }
    methods:  GET
visite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Visite:show" }
    methods:  GET



