AppBundle\Entity\Client:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'auth-token']
        nom:
            groups: ['user','auth-token']
        usename:
            groups: ['user','auth-token']
        ville:
            groups: ['user','auth-token']