AppBundle\Entity\Matiere:
    exclusion_policy: none
    properties:
        id:
            groups: ['matiere', 'programme', 'full','partie']
        titre:
             groups: ['matiere', 'programme', 'full','partie']
        description:
             groups: ['matiere', 'programme', 'full']
        categorie:
             groups: ['matiere', 'programme', 'full']
        poids:
             groups: ['matiere', 'programme', 'full']
        otherRessourcesLink:
             groups: ['matiere', 'programme', 'full']      
        image:
             groups: ['matiere', 'programme', 'full']
        otherRessourcesLink:
             groups: ['matiere', 'programme', 'full']
        contenu:
             groups: ['matiere', 'programme', 'full'] 
        ressources:
             groups: ['matiere', 'programme', 'full']                         
    callback_methods:
        pre_serialize: ['getOtherRessourcesLink','getContenu']
                