AppBundle\Entity\Produit:
    exclusion_policy: none
    properties:
        id:
            groups: ['produit','ligne','commende','full']
        nom:
            groups: ['produit','ligne','commende','full']
        description:
            groups: ['produit','ligne','commende'] 
        cout:
            groups: ['produit','ligne','commende','full'] 
              