AppBundle\Entity\Partie:
    exclusion_policy: none
    properties:
        id:
            groups: ['question','partie', 'full']
        titre:
             groups: ['partie', 'full']
        cours:
             groups: ['partie', 'full']             
        prerequis:
             groups: ['partie', 'full']
        matiere:
             groups: ['partie']
        objectif:
             groups: ['partie', 'full']
        qcm:
             groups: ['partie', 'full']            