AppBundle\Entity\Produit:
    exclusion_policy: none
    properties:
        id:
            groups: ['produit','ligne','commende','rendezvous','full']
        nom:
            groups: ['produit','ligne','commende','rendezvous','full']
        description:
            groups: ['produit','ligne','commende','full'] 
        cout:
            groups: ['produit','ligne','commende','full'] 
        stored:
            groups: ['produit','ligne','commende','full']              