AppBundle\Entity\User:
    exclusion_policy: none
    properties:
        apiKey:
            groups: ['user', 'auth-token','full']
        id:
            groups: ['rendezvous','user', 'auth-token','parent','commende','full']            
        nom:
            groups: ['rendezvous','user','parent','commende','full','last']
        entreprise:
            groups: ['user','parent','full']
        username:
            groups: ['user','auth-token','full']
        abonnement:
            groups: ['user','parent']            
        email:
            groups: ['user','full']
        invited:
            groups: ['user']
        phone:
            groups: ['rendezvous','user','full']   
        ville:
            groups: ['user','full']
        pays:
            groups: ['user']           
        receiveRequests:
            groups: ['parent']
        secteur:
            groups: ['user']
        parent:
            groups: ['user','parent']