AppBundle\Entity\Partie:
    exclusion_policy: none
    properties:
        id:
            groups: ['question','partie', 'full']
        titre:
             groups: ['partie', 'full']
        matiere:
             groups: ['partie']
    virtual_properties:
        getQcm:
            serialized_name: qcm
            type: integer               
        getCours:
            serialized_name: cours
            type: string
        getObjectif:
            serialized_name: objectif
            type: string 
        getPrerequis:
            serialized_name: prerequis
            type: string                        