AppBundle\Entity\Rendezvous:
    exclusion_policy: none
    properties:
        id:
            groups: ['pointvente','rendezvous','full']
        commentaire:
            groups: ['pointvente','rendezvous','full']                                    
        quantite:
            groups: ['rendezvous','full']
        user:
            groups: ['rendezvous','full']
        createdBy:
            groups: ['rendezvous','full'] 
        pointVente:
            groups: ['full']                        
        dateat:
            groups: ['map','pointvente','rendezvous','full']
            type: DateTime<'Y-m-d'> 
        persist:
            groups: ['pointvente','rendezvous','full']            
        produitnonvendu:
            groups: ['pointvente','rendezvous','full']            
        date:
            groups: ['pointvente','rendezvous','full']
            expose: true
            type: DateTime<'Y-m-d'>  
        passdays:
             groups: ['pointvente','rendezvous','full'] 
        previsions:
             groups: ['rendezvous','full']          
        stored:
            groups: ['rendezvous','full']                