AppBundle\Entity\Secteur:
    exclusion_policy: none
    properties:
        id:
            groups: ['pointvente','secteur','user']
        nom:
            groups: ['pointvente','secteur','user']
        ville:
            groups: ['pointvente','secteur'] 
        stored:
            groups: ['pointvente','secteur'] 
        description:
            groups: ['secteur'] 