AppBundle\Entity\Commende:
    exclusion_policy: none
    properties:
        id:
            groups: ['commende','full']
        pointVente:
            groups: ['commende','full']
        status:
            groups: ['commende','full']  
        numFacture:
            groups: ['commende','full']                      
        lignes:
            groups: ['full']
        date:
            groups: ['commende','full']
            expose: true
            type: DateTime<'Y-m-d'> 
              