AppBundle\Entity\Article:
    exclusion_policy: none
    properties:
        id:
            groups: ['article', 'partie', 'full']
        titre:
             groups: ['article', 'full']
        introduction:
             groups: ['article', 'full']
        image:
             groups: ['article', 'full']
        contents:
             groups: ['article', 'full']