AppBundle\Entity\PointVente:
    exclusion_policy: none
    properties:
        id:
            groups: ['map','rendezvous','commende','pointvente','full','last']
        nom:
            groups: ['map','rendezvous','commende','pointvente','full']
        telephone:
            groups: ['map','rendezvous','commende','pointvente','full'] 
        rendezvous:
            groups: ['map','pointvente','rendezvous']           
        ville:
            groups: ['map','rendezvous','commende','pointvente','full'] 
        type:
            groups: ['map','rendezvous','commende','pointvente','full'] 
        quartier:
            groups: ['map','rendezvous','commende','pointvente','full'] 
        adresse:
            groups: ['map','rendezvous','commende','pointvente','full'] 
        secteur:
            accessor:
               getter: getSecteur
            groups: ['map','rendezvous','pointvente','full']
        lastCommende:
            groups: ['map','pointvente','full']
        firstCommende:
            groups: ['map','pointvente','full']            
        stored:
            groups: ['rendezvous','pointvente','full']
        visited:
            groups: ['map']
        long:
            groups: ['map','rendezvous','pointvente','commende','full'] 
        lat:
            groups: ['map','rendezvous','pointvente','commende','full'] 
        date:
            groups: ['commende','full','rendezvous','last','pointvente']
            expose: true
            type: DateTime<'Y-m-d'> 
