AppBundle\Entity\PointVente:
    exclusion_policy: none
    properties:
        id:
            groups: ['rendezvous','commende','pointvente']
        nom:
            groups: ['rendezvous','commende','pointvente']
        telephone:
            groups: ['rendezvous','commende','pointvente'] 
        ville:
            groups: ['rendezvous','commende','pointvente'] 
        type:
            groups: ['rendezvous','commende','pointvente'] 
        quartier:
            groups: ['rendezvous','commende','pointvente'] 
        adresse:
            groups: ['rendezvous','commende','pointvente'] 
        secteur:
            groups: ['rendezvous','pointvente']
        lastLines:
            groups: ['rendezvous']
        stored:
            groups: ['rendezvous','pointvente'] 
