AppBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'auth-token']
        nom:
            groups: ['user','auth-token']
        usename:
            groups: ['user','auth-token']