AppBundle\Entity\Matiere:
    exclusion_policy: none
    properties:
        id:
            groups: ['matiere', 'programme', 'full','partie']
        titre:
             groups: ['matiere', 'programme', 'full','partie']
        description:
             groups: ['matiere', 'programme', 'full']
        categorie:
             groups: ['matiere', 'programme', 'full']
        poids:
             groups: ['matiere', 'programme', 'full']
        otherRessourcesLink:
             groups: ['matiere', 'programme', 'full']      
        image:
             groups: ['matiere', 'programme', 'full']
    virtual_properties:
        getContenu:
            serialized_name: contenu
            type: integer 
            groups: ['matiere', 'programme', 'full']                             
        getOtherRessourcesLink:
            serialized_name: otherRessourcesLink
            type: string  
            groups: ['matiere', 'programme', 'full']                 