AppBundle\Entity\Objectif:
    exclusion_policy: none
    properties:
        id:
            groups: ['matiere','programme', ]
        titre:
             groups: ['matiere','programme']
        description:
             groups: ['matiere','programme']