AppBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'auth-token','parent','commende']
        nom:
            groups: ['user','parent','commende']
        entreprise:
            groups: ['user','parent']
        username:
            groups: ['user','auth-token']
        abonnement:
            groups: ['user','parent']            
        email:
            groups: ['user']
        invited:
            groups: ['user']
        phone:
            groups: ['user']   
        ville:
            groups: ['user']
        pays:
            groups: ['user']           
        receiveRequests:
            groups: ['user']
        secteur:
            groups: ['user']
        parent:
            groups: ['parent']