AppBundle\Entity\Candidat:
    exclusion_policy: none
    properties:
        studentId:
             groups: ['candidat', 'info']
        email:
             groups: ['candidat', 'info']             
        displayName:
             groups: ['candidat', 'info']
        parentPhone:
             groups: ['candidat', 'info']
        etablissement:
             groups: ['candidat', 'info']             
        branche:
             groups: ['candidat', 'info']
        ville:
             groups: ['candidat', 'info']