AppBundle\Entity\User:
    exclusion_policy: none
    properties:
        apiKey:
            groups: ['user', 'auth-token']
        id:
            groups: ['rendezvous','user', 'auth-token','parent','commende']            
        nom:
            groups: ['rendezvous','user','parent','commende']
        entreprise:
            groups: ['user','parent']
        username:
            groups: ['user','auth-token']
        abonnement:
            groups: ['user','parent']            
        email:
            groups: ['user']
        invited:
            groups: ['user']
        phone:
            groups: ['rendezvous','user']   
        ville:
            groups: ['user']
        pays:
            groups: ['user']           
        receiveRequests:
            groups: ['parent']
        secteur:
            groups: ['user',]
        parent:
            groups: ['parent']