AppBundle\Entity\Ligne:
    exclusion_policy: none
    properties:
        id:
            groups: ['ligne','rendezvous','full']
        produit:
            groups: ['ligne','rendezvous','full']
        quantite:
            groups: ['ligne','rendezvous','full']
              