AppBundle\Entity\Programme:
    exclusion_policy: none
    properties:
        id:
            groups: ['programme', 'full','abonnement']
        nom:
             groups: ['programme', 'full','abonnement']
        price:
             groups: ['programme', 'full','abonnement']                
        ecole:
             groups: ['programme', 'full','abonnement']
        programme:
             groups: ['programme', 'full','abonnement']              
        image:
             groups: [ 'full']
        abreviation:
             groups: ['programme', 'full']
        type:
             groups: ['programme', 'full']
        session:
             groups: ['programme', 'full']
        descriptionEcole:
             groups: [ 'full']
        descriptionConcours:
             groups: ['full']
        nombrePlace:
             groups: ['programme', 'full']
        dateConcours:
             groups: ['programme', 'full']
             expose: true
             type: DateTime<'Y-m-d'>           
        dateDossier:
             groups: [ 'full']
             expose: true
             type: DateTime<'Y-m-d'> 
        lien:
             groups: ['programme', 'full']
        contact:
             groups: [ 'full']
        resultats:
             groups: ['programme', 'full']           
    callback_methods:
        pre_serialize: ['getProgramme','getPrice']