AppBundle\Entity\Ligne:
    exclusion_policy: none
    properties:
        id:
            groups: ['commende','ligne']
        produit:
            groups: ['commende','ligne']
        quantite:
            groups: ['commende','ligne']
              