AppBundle\Entity\Concours:
    exclusion_policy: none
    properties:
        id:
            groups: ['session','concours', 'full','abonnement']
        nom:
             groups: ['session','concours', 'full','abonnement']               
        ecole:
             groups: ['session','concours', 'full']
        descriptionEcole:
             groups: ['concours', 'full']
        descriptionConcours:
             groups: ['session','concours','full'] 
        abreviation:
             groups: ['session','concours', 'full' ,'abonnement']                               
        image:
             groups: ['session', 'concours','full','abonnement']
        contacts:
             groups: ['concours', 'full']  
        callback_methods:
            pre_serialize: ['getImageUrl']                 