AppBundle\Entity\AuthToken:
    exclusion_policy: ALL
    properties:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']