AppBundle\Entity\Content:
    exclusion_policy: none
    properties:
        id:
            groups: ['article', 'full','content']
        subtitle:
             groups: ['article', 'full','content']
        text:
             groups: ['article', 'full','content']
        image:
             groups: ['article', 'full','content']