AppBundle\Entity\Question:
    exclusion_policy: none
    properties:
        id:
            groups: ['question', 'full']
        type:
             groups: ['question', 'full']
        math:
             groups: ['question', 'full']
        text:
             groups: ['question', 'full']
        image:
            groups: ['question', 'full']
        showLink:
            groups: ['question', 'full']
        validated:
            groups: ['question', 'full']
        explication:
            groups: ['question', 'full']
        partie:
            groups: ['question']
        objectif:
            groups: ['question']
        time:
            groups: ['question', 'full']
        rep:
            groups: ['question', 'full']
        note:
            groups: ['question', 'full']
        propA:
            groups: ['question', 'full']
        propB:
            groups: ['question', 'full']
        propC:
            groups: ['question', 'full']
        propD:
            groups: ['question', 'full']
        propE:
            groups: ['question', 'full']