AppBundle\Entity\Commende:
    exclusion_policy: none
    properties:
        id:
            groups: ['commende','full','rendezvous']
        pointVente:
            groups: ['commende','full','last']
        status:
            groups: ['commende','full']  
        numFacture:
            groups: ['commende','full']   
        user:
            groups: ['commende','full','last'] 
        terminated:
            groups: ['commende','full'] 
        stored:
            groups: ['commende','full']                                               
        lignes:
            groups: ['full']
        date:
            groups: ['commende','full','rendezvous','last']
            expose: true
            type: DateTime<'Y-m-d'> 
              