AppBundle\Entity\Info:
    exclusion_policy: none
    properties:
        email:
             groups: ['info', 'full']             
        displayName:
             groups: ['info', 'full']
        photoURL:
             groups: ['info', 'full']
        candidat:
             groups: ['info', 'full']