<?php

namespace Pwm\MessagerBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
		  /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findList(){
         $qb = $this->createQueryBuilder('a')
          ->where('a.type is NULL')
          ->orWhere('a.type =:type')->setParameter('type','public');;
          return $qb->getQuery()->getResult();
  }


}
