<?php

namespace Pwm\AdminBundle\Repository;

/**
 * AmbassadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmbassadorRepository extends \Doctrine\ORM\EntityRepository
{
}
