<?php

namespace Pwm\AdminBundle\Repository;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends \Doctrine\ORM\EntityRepository
{
	 /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findOneOrNull($studentId){
         $qb = $this->createQueryBuilder('a')
         ->where('a.email=:studentId')->setParameter('studentId',$studentId);
          return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
  }

   public function findNotProfilFilled(){
         $qb = $this->createQueryBuilder('a')
         ->where('a.phone is NULL or a.niveau is NULL or a.serie is NULL');
          return $qb->getQuery()->setMaxResults(50)->getResult();
  }

   public function findSubscribersExpired(){
         $qb = $this->createQueryBuilder('i')->join('i.abonnements', 'a') ->leftJoin('a.session', 's')
          ->where('a.endDate<=:endDate')->setParameter('endDate',new \DateTime())
          ->andWhere('s.archived=:archived')->setParameter('archived',false);
          return $qb->getQuery()->getResult();
  }
  
   public function findSubscribersByBundle($package){
         $qb = $this->createQueryBuilder('i')->join('i.abonnements', 'a') ->leftJoin('a.session', 's')
          ->where('a.plan=:plan')->setParameter('plan',$package)
         ->andWhere('s.archived=:archived')->setParameter('archived',false);
          return $qb->getQuery()->getResult();
  }
}
