<?php

namespace Pwm\AdminBundle\Repository;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends \Doctrine\ORM\EntityRepository
{
	 /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findOneOrNull($studentId){
         $qb = $this->createQueryBuilder('a')
         ->where('a.email=:studentId')->setParameter('studentId',$studentId);
          return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
  }

   public function findNotProfilFilled(){
         $qb = $this->createQueryBuilder('a')
         ->where('a.serie is NULL or a.niveau is NULL or a.dateMax is NULL');
          return $qb->getQuery()->getResult();
  }
}
