<?php

namespace Pwm\AdminBundle\Repository;
use AppBundle\Entity\Session;
/**
 * RessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceRepository extends \Doctrine\ORM\EntityRepository
{
     public function findNewRessources(Session $session){
       $now=new \DateTime();
       $now->modify('-15 day');
         $qb = $this->createQueryBuilder('r')
         >where('r.session=:session or r.isPublic=:ispublic')->setParameter('session',$session)->setParameter('ispublic',true)
          ->andWhere('a.date>:date')->setParameter('date',$now);
          return $qb->getQuery()->getResult();
  }

      public function findRessources(Session $session){
         $qb = $this->createQueryBuilder('r')
         ->where('r.session=:session or r.isPublic=:ispublic')->setParameter('session',$session)->setParameter('ispublic',true);
          return $qb->getQuery()->getResult();
  } 
}
