pub_index_json:
    path:     /pub/json
    defaults: { _controller: "MessagerBundle:Pub:jsonIndex", }
    methods:  GET

sending_index_json:
    path:     /sending/json
    defaults: { _controller: "MessagerBundle:Sending:jsonIndex" }
    methods:  GET

sending_edit_json:
    path:     /sending/edit/message/{id}/json
    defaults: { _controller: "MessagerBundle:Sending:editJson","id":0 }
    methods:  [GET, POST]

sending_new_json:
    path:     /registration/{registrationId}/new/json
    defaults: { _controller: "MessagerBundle:Sending:newJson","registrationId":'null' }
    methods:  [GET, POST]

notification_show_json:
    path:     /notification/{id}/show/json
    defaults: { _controller: "MessagerBundle:Notification:showJson" }
    methods:  [GET, POST]
  
