notification_index:
    path:     /
    defaults: { _controller: "MessagerBundle:Notification:index" }
    methods:  GET

notification_show:
    path:     /{id}/show
    defaults: { _controller: "MessagerBundle:Notification:show" }
    methods:  [GET, POST]

notification_send:
    path:     /{id}/send
    defaults: { _controller: "MessagerBundle:Notification:send" }
    methods:  [GET, POST]


notification_resent:
    path:     /resent/{id}
    defaults: { _controller: "MessagerBundle:Notification:resent","id":0  }
    methods:  [GET, POST]
    
notification_resent_fron_cron:
    path:     /resent/from/cron/job/{id}
    defaults: { _controller: "MessagerBundle:Notification:resentFroCronJob","id":0  }
    methods:  [GET, POST]
 

notification_sent_too:
    path:     /sent/too/{id}
    defaults: { _controller: "MessagerBundle:Notification:sendToo" }
    methods:  [GET, POST]


notification_rate:
    path:     /{id}/rate
    defaults: { _controller: "MessagerBundle:Notification:getRate" }
    methods:  [GET, POST]

notification_reading:
    path:     /{id}/reading
    defaults: { _controller: "MessagerBundle:Notification:getReading" }
    methods:  [GET, POST]

notification_number_dest:
    path:     /{id}/number/dest
    defaults: { _controller: "MessagerBundle:Notification:getDestNumber" }
    methods:  [GET, POST]

notification_new:
    path:     /new/{id}
    defaults: { _controller: "MessagerBundle:Notification:new","id":0 }
    methods:  [GET, POST]

sms_send:
    path:     /sms/send
    defaults: { _controller: "MessagerBundle:Notification:sendSMS" }
    methods:  [GET, POST]



notification_edit:
    path:     /{id}/edit
    defaults: { _controller: "MessagerBundle:Notification:edit" }
    methods:  [GET, POST]

notification_delete:
    path:     /{id}/delete
    defaults: { _controller: "MessagerBundle:Notification:delete" }
    methods:  DELETE
