pub_index:
    path:     /
    defaults: { _controller: "MessagerBundle:Pub:index" }
    methods:  GET

pub_show:
    path:     /{id}/show
    defaults: { _controller: "MessagerBundle:Pub:show" }
    methods:  GET

pub_new:
    path:     /new
    defaults: { _controller: "MessagerBundle:Pub:new" }
    methods:  [GET, POST]

pub_edit:
    path:     /{id}/edit
    defaults: { _controller: "MessagerBundle:Pub:edit" }
    methods:  [GET, POST]

pub_delete:
    path:     /{id}/delete
    defaults: { _controller: "MessagerBundle:Pub:delete" }
    methods:  DELETE
