sending_index:
    path:     /
    defaults: { _controller: "MessagerBundle:Sending:index" }
    methods:  GET

sending_show:
    path:     /{id}/show
    defaults: { _controller: "MessagerBundle:Sending:show" }
    methods:  GET

sending_new:
    path:     /new
    defaults: { _controller: "MessagerBundle:Sending:new" }
    methods:  [GET, POST]

sending_edit:
    path:     /{id}/edit
    defaults: { _controller: "MessagerBundle:Sending:edit" }
    methods:  [GET, POST]

sending_delete:
    path:     /{id}/delete
    defaults: { _controller: "MessagerBundle:Sending:delete" }
    methods:  DELETE
